source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'WFApplyChargePile_Example' do
  pod 'WFApplyChargePile', :path => '../'

  target 'WFApplyChargePile_Tests' do
    inherit! :search_paths

    
  end
end
