use_frameworks!

platform :ios, '8.0'

target 'WFApplyChargePile_Example' do
  pod 'WFApplyChargePile', :path => '../'

  target 'WFApplyChargePile_Tests' do
    inherit! :search_paths

    
  end
end
